/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControllerAdmin;
import javax.swing.JOptionPane;
import Control.ControllerMahasiswa;
import Model.Akun;
import Model.Keuangan;
import Model.Mahasiswa;
import Model.Matakuliah;
import Model.Nilai;
import Model.Perwalian;
import View.Alert.DarkAlert;
import java.awt.Color;
import java.awt.Label;
import java.awt.TextField;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.event.MouseInputListener;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kingt
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Percobaan
     */
    private Akun acc;

    public Admin() {
        initComponents();
        setupButtonUI();
        setupClickButton();
        tampilDataMahasiswa();
        daftarMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        daftarMatakuliah.setVisible(false);
        tableDark3.fixTable1(jScrollPane7);
        tableDark3.fixTable1(jScrollPane4);
        tableDark3.fixTable1(jScrollPane3);
    }

    public Admin(Akun acc) {
        this.acc = acc;
        initComponents();
        setupButtonUI();
        setupClickButton();
        daftarMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        daftarMatakuliah.setVisible(false);
        tableDark3.fixTable1(jScrollPane3);
        tableDark3.fixTable1(jScrollPane4);
    }

    private void setupClickButton() {
        JButton[] btns = {jButton7, jButton8, jButton9, jButton10, jButton11, jButton12, jButton13};
        for (JButton btn : btns) {
            btn.setBackground(new Color(51, 51, 51));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseInputListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(150, 150, 150));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(51, 51, 51));
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 30));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(51, 51, 51));
                }

                @Override
                public void mouseDragged(MouseEvent e) {
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
        }
    }

    // Metode untuk mengatur tampilan dan perilaku tombol
    private void setupButtonUI() {
        JButton[] btns = {jButton1, jButton2, jButton3, jButton4, jButton6};
        for (JButton btn : btns) {
            btn.setBackground(new Color(33, 32, 36));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseInputListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(102, 102, 102));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(33, 32, 36));
                }

                @Override
                public void mouseDragged(MouseEvent e) {
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        daftarMahasiswa = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        daftarMahasiswaTable = new View.Table.TableDark();
        jPanel62 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        dosenWali = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        semesterAktif = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jPanel64 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        programStudi = new javax.swing.JTextField();
        batasStudi = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nomor = new javax.swing.JTextField();
        jPanel69 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        daftarMatakuliah = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDark3 = new View.Table.TableDark();
        jPanel70 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        dosenWali1 = new javax.swing.JTextField();
        nim1 = new javax.swing.JTextField();
        nama1 = new javax.swing.JTextField();
        semesterAktif1 = new javax.swing.JTextField();
        status1 = new javax.swing.JTextField();
        jPanel72 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        batasStudi1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        nomor1 = new javax.swing.JTextField();
        jPanel77 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        keuanganKuliah = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ukt1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        ukv1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        dpp = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        ukt = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        biayaSks = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        dpp_wajib = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        totalDenda = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        hariPerwalian = new javax.swing.JTextField();
        tahunPerwalian = new javax.swing.JTextField();
        bulanPerwalian = new javax.swing.JTextField();
        hariPembayaran = new javax.swing.JTextField();
        tahunPembayaran = new javax.swing.JTextField();
        bulanPembayaran = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        JadwakMahasiswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(33, 32, 36));
        sidePanel.setPreferredSize(new java.awt.Dimension(60, 500));

        jPanel4.setBackground(new java.awt.Color(33, 32, 36));
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 150));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButton6.setBackground(new java.awt.Color(33, 32, 36));
        jButton6.setForeground(new java.awt.Color(50, 98, 227));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_graduation_cap_20px_1.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        sidePanel.add(jPanel4);

        jButton1.setBackground(new java.awt.Color(33, 32, 36));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_registration_20px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(33, 32, 36));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Document_20px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton2);

        jButton4.setBackground(new java.awt.Color(33, 32, 36));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_online_payment_20px_4.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton4);

        jButton3.setBackground(new java.awt.Color(33, 32, 36));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_event_accepted_tentatively_20px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        sidePanel.add(jButton3);

        jPanel1.add(sidePanel, java.awt.BorderLayout.WEST);

        PanelContent.setMinimumSize(new java.awt.Dimension(0, 0));
        PanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(23, 23, 26));
        dashboard.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel3.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(193, 195, 199));
        jLabel3.setText("Dashboard");
        jLabel3.setIconTextGap(0);

        jLabel4.setForeground(new java.awt.Color(193, 195, 199));
        jLabel4.setText("Sistem Informasi Akademik");

        jPanel8.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Varian-Logo-Itenas2-09-768x195.png"))); // NOI18N

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(dashboardLayout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(192, 192, 192))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        PanelContent.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        dashboard.getAccessibleContext().setAccessibleName("");

        daftarMahasiswa.setBackground(new java.awt.Color(23, 23, 26));
        daftarMahasiswa.setPreferredSize(new java.awt.Dimension(900, 500));
        daftarMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMahasiswaMouseClicked(evt);
            }
        });
        daftarMahasiswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(193, 195, 199));
        jLabel9.setText("Daftar Mahasiswa");
        jLabel9.setIconTextGap(0);
        daftarMahasiswa.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 48, -1, 38));

        jLabel10.setForeground(new java.awt.Color(193, 195, 199));
        jLabel10.setText("Sistem Informasi Akademik");
        daftarMahasiswa.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        daftarMahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Status", "Dosen Wali", "Semester", "Batas Studi", "Email", "Nomor", "Program Studi"
            }
        ));
        daftarMahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(daftarMahasiswaTable);

        daftarMahasiswa.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 670, 155));

        jPanel62.setBackground(new java.awt.Color(33, 32, 36));
        jPanel62.setForeground(new java.awt.Color(193, 195, 199));
        jPanel62.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setForeground(new java.awt.Color(193, 195, 199));
        jLabel81.setText("Nama Mahasiswa");
        jLabel81.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel62.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jPanel63.setBackground(new java.awt.Color(33, 32, 36));
        jPanel63.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel63.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel82.setText("Nama Mahasiswa");
        jLabel82.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel63.add(jLabel82);

        jPanel62.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        daftarMahasiswa.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 104, -1));

        jPanel7.setBackground(new java.awt.Color(33, 32, 36));
        jPanel7.setForeground(new java.awt.Color(193, 195, 199));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(193, 195, 199));
        jLabel19.setText("Dosen Wali");
        jLabel19.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 104, -1));

        jPanel6.setBackground(new java.awt.Color(33, 32, 36));
        jPanel6.setForeground(new java.awt.Color(193, 195, 199));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(193, 195, 199));
        jLabel18.setText("Status");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 104, -1));

        jPanel5.setBackground(new java.awt.Color(33, 32, 36));
        jPanel5.setForeground(new java.awt.Color(193, 195, 199));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(193, 195, 199));
        jLabel17.setText("NIM");
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 104, -1));

        dosenWali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dosenWali.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(dosenWali, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 220, 30));

        nim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nim.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, 30));

        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 220, 30));

        semesterAktif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        semesterAktif.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(semesterAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 220, 30));

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 220, 30));

        jPanel64.setBackground(new java.awt.Color(33, 32, 36));
        jPanel64.setForeground(new java.awt.Color(193, 195, 199));
        jPanel64.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setForeground(new java.awt.Color(193, 195, 199));
        jLabel83.setText("Email");
        jLabel83.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel64.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jPanel65.setBackground(new java.awt.Color(33, 32, 36));
        jPanel65.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel65.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel84.setText("Nama Mahasiswa");
        jLabel84.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel65.add(jLabel84);

        jPanel64.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        daftarMahasiswa.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 104, -1));

        jPanel66.setBackground(new java.awt.Color(33, 32, 36));
        jPanel66.setForeground(new java.awt.Color(193, 195, 199));
        jPanel66.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setForeground(new java.awt.Color(193, 195, 199));
        jLabel85.setText("Program Studi");
        jLabel85.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel66.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 104, -1));

        jPanel67.setBackground(new java.awt.Color(33, 32, 36));
        jPanel67.setForeground(new java.awt.Color(193, 195, 199));
        jPanel67.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setForeground(new java.awt.Color(193, 195, 199));
        jLabel86.setText("Nomor");
        jLabel86.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel67.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 104, -1));

        jPanel68.setBackground(new java.awt.Color(33, 32, 36));
        jPanel68.setForeground(new java.awt.Color(193, 195, 199));
        jPanel68.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setForeground(new java.awt.Color(193, 195, 199));
        jLabel87.setText("Batas Studi");
        jLabel87.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel68.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 80, -1));

        daftarMahasiswa.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 104, -1));

        programStudi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        programStudi.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(programStudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 220, 30));

        batasStudi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batasStudi.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(batasStudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 220, 30));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, 30));

        nomor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomor.setForeground(new java.awt.Color(102, 102, 102));
        daftarMahasiswa.add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 220, 30));

        jPanel69.setBackground(new java.awt.Color(33, 32, 36));
        jPanel69.setForeground(new java.awt.Color(193, 195, 199));
        jPanel69.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setForeground(new java.awt.Color(193, 195, 199));
        jLabel88.setText("Semester Aktif");
        jLabel88.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel69.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMahasiswa.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 104, -1));

        jButton7.setForeground(new java.awt.Color(193, 195, 199));
        jButton7.setText("Tambah");
        jButton7.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        daftarMahasiswa.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 100, -1));

        jButton8.setForeground(new java.awt.Color(193, 195, 199));
        jButton8.setText("Hapus");
        jButton8.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        daftarMahasiswa.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 120, -1));

        jButton13.setForeground(new java.awt.Color(193, 195, 199));
        jButton13.setText("Update");
        jButton13.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        daftarMahasiswa.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 90, -1));

        PanelContent.add(daftarMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));
        daftarMahasiswa.getAccessibleContext().setAccessibleName("");

        daftarMatakuliah.setBackground(new java.awt.Color(23, 23, 26));
        daftarMatakuliah.setPreferredSize(new java.awt.Dimension(1000, 500));
        daftarMatakuliah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(193, 195, 199));
        jLabel14.setText("Daftar Matakuliah");
        jLabel14.setIconTextGap(0);
        daftarMatakuliah.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 38));

        jLabel15.setForeground(new java.awt.Color(193, 195, 199));
        jLabel15.setText("Sistem Informasi Akademik");
        daftarMatakuliah.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        tableDark3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Matakuliah", "SKS", "Kelas", "Jenis", "Sisa", "Status Awal", "Hari", "Jam"
            }
        ));
        tableDark3.setPreferredSize(new java.awt.Dimension(700, 180));
        tableDark3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDark3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableDark3);

        daftarMatakuliah.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, 670, 150));

        jPanel70.setBackground(new java.awt.Color(33, 32, 36));
        jPanel70.setForeground(new java.awt.Color(193, 195, 199));
        jPanel70.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel89.setForeground(new java.awt.Color(193, 195, 199));
        jLabel89.setText("Matakuliah");
        jLabel89.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel70.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jPanel71.setBackground(new java.awt.Color(33, 32, 36));
        jPanel71.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel71.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel90.setText("Nama Mahasiswa");
        jLabel90.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel71.add(jLabel90);

        jPanel70.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        daftarMatakuliah.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 104, -1));

        jPanel11.setBackground(new java.awt.Color(33, 32, 36));
        jPanel11.setForeground(new java.awt.Color(193, 195, 199));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(193, 195, 199));
        jLabel20.setText("Kelas");
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMatakuliah.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 104, -1));

        jPanel12.setBackground(new java.awt.Color(33, 32, 36));
        jPanel12.setForeground(new java.awt.Color(193, 195, 199));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(193, 195, 199));
        jLabel21.setText("Jumlah SKS");
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 90, -1));

        daftarMatakuliah.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 104, -1));

        jPanel13.setBackground(new java.awt.Color(33, 32, 36));
        jPanel13.setForeground(new java.awt.Color(193, 195, 199));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(193, 195, 199));
        jLabel22.setText("Kode");
        jLabel22.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMatakuliah.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 104, -1));

        dosenWali1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dosenWali1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(dosenWali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 220, 30));

        nim1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nim1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(nim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, 30));

        nama1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 220, 30));

        semesterAktif1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        semesterAktif1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(semesterAktif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 220, 30));

        status1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 220, 30));

        jPanel72.setBackground(new java.awt.Color(33, 32, 36));
        jPanel72.setForeground(new java.awt.Color(193, 195, 199));
        jPanel72.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel91.setForeground(new java.awt.Color(193, 195, 199));
        jLabel91.setText("Hari");
        jLabel91.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel72.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jPanel73.setBackground(new java.awt.Color(33, 32, 36));
        jPanel73.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel73.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel92.setText("Nama Mahasiswa");
        jLabel92.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel73.add(jLabel92);

        jPanel72.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        daftarMatakuliah.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 104, -1));

        jPanel75.setBackground(new java.awt.Color(33, 32, 36));
        jPanel75.setForeground(new java.awt.Color(193, 195, 199));
        jPanel75.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel94.setForeground(new java.awt.Color(193, 195, 199));
        jLabel94.setText("Jam");
        jLabel94.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel75.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMatakuliah.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 104, -1));

        jPanel76.setBackground(new java.awt.Color(33, 32, 36));
        jPanel76.setForeground(new java.awt.Color(193, 195, 199));
        jPanel76.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setForeground(new java.awt.Color(193, 195, 199));
        jLabel95.setText("Kapasitas");
        jLabel95.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel76.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 80, -1));

        daftarMatakuliah.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 104, -1));

        batasStudi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batasStudi1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(batasStudi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, 30));

        email1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 220, 30));

        nomor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomor1.setForeground(new java.awt.Color(102, 102, 102));
        daftarMatakuliah.add(nomor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 220, 30));

        jPanel77.setBackground(new java.awt.Color(33, 32, 36));
        jPanel77.setForeground(new java.awt.Color(193, 195, 199));
        jPanel77.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setForeground(new java.awt.Color(193, 195, 199));
        jLabel96.setText("Jenis");
        jLabel96.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel77.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarMatakuliah.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 104, -1));

        jButton9.setForeground(new java.awt.Color(193, 195, 199));
        jButton9.setText("Tambah");
        jButton9.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        daftarMatakuliah.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 90, -1));

        jButton10.setForeground(new java.awt.Color(193, 195, 199));
        jButton10.setText("Bersihkan");
        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        daftarMatakuliah.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 120, -1));

        PanelContent.add(daftarMatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        keuanganKuliah.setBackground(new java.awt.Color(23, 23, 26));
        keuanganKuliah.setPreferredSize(new java.awt.Dimension(1000, 500));
        keuanganKuliah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(33, 32, 36));
        jLabel16.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(193, 195, 199));
        jLabel16.setText("Denda");
        jLabel16.setIconTextGap(0);
        keuanganKuliah.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 282, -1, -1));

        jLabel37.setForeground(new java.awt.Color(193, 195, 199));
        jLabel37.setText("Sistem Informasi Akademik");
        keuanganKuliah.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        ukt1.setBackground(new java.awt.Color(33, 32, 36));
        ukt1.setForeground(new java.awt.Color(193, 195, 199));
        ukt1.setMinimumSize(new java.awt.Dimension(30, 15));
        ukt1.setPreferredSize(new java.awt.Dimension(120, 29));
        ukt1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel43.setForeground(new java.awt.Color(193, 195, 199));
        jLabel43.setText("UKT (Uang Kuliah Tetap)");
        jLabel43.setPreferredSize(new java.awt.Dimension(130, 29));
        ukt1.add(jLabel43);

        keuanganKuliah.add(ukt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 212, 152, -1));

        ukv1.setBackground(new java.awt.Color(33, 32, 36));
        ukv1.setForeground(new java.awt.Color(193, 195, 199));
        ukv1.setMinimumSize(new java.awt.Dimension(32, 15));
        ukv1.setPreferredSize(new java.awt.Dimension(120, 29));
        ukv1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel44.setForeground(new java.awt.Color(193, 195, 199));
        jLabel44.setText("Biaya/SKS");
        jLabel44.setPreferredSize(new java.awt.Dimension(140, 29));
        ukv1.add(jLabel44);

        keuanganKuliah.add(ukv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, 152, -1));

        dpp.setBackground(new java.awt.Color(33, 32, 36));
        dpp.setForeground(new java.awt.Color(193, 195, 199));
        dpp.setMinimumSize(new java.awt.Dimension(58, 15));
        dpp.setPreferredSize(new java.awt.Dimension(120, 29));
        dpp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel46.setForeground(new java.awt.Color(193, 195, 199));
        jLabel46.setText("DPP Wajib");
        jLabel46.setPreferredSize(new java.awt.Dimension(130, 29));
        dpp.add(jLabel46);

        keuanganKuliah.add(dpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 177, 152, -1));

        jPanel42.setBackground(new java.awt.Color(33, 32, 36));
        jPanel42.setForeground(new java.awt.Color(193, 195, 199));
        jPanel42.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel54.setForeground(new java.awt.Color(193, 195, 199));
        jLabel54.setText("Tanggal Perwalian");
        jLabel54.setPreferredSize(new java.awt.Dimension(130, 29));
        jPanel42.add(jLabel54);

        keuanganKuliah.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 306, 152, -1));

        jPanel45.setBackground(new java.awt.Color(33, 32, 36));
        jPanel45.setForeground(new java.awt.Color(193, 195, 199));
        jPanel45.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel45.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel55.setForeground(new java.awt.Color(193, 195, 199));
        jLabel55.setText("Tanggal Pembayaran");
        jLabel55.setPreferredSize(new java.awt.Dimension(130, 29));
        jPanel45.add(jLabel55);

        keuanganKuliah.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 342, 152, -1));

        jPanel49.setBackground(new java.awt.Color(33, 32, 36));
        jPanel49.setForeground(new java.awt.Color(193, 195, 199));
        jPanel49.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel49.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        ukt.setForeground(new java.awt.Color(193, 195, 199));
        ukt.setText("NIM");
        ukt.setPreferredSize(new java.awt.Dimension(200, 29));
        ukt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uktMouseClicked(evt);
            }
        });
        jPanel49.add(ukt);

        keuanganKuliah.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 212, 218, 29));

        jPanel50.setBackground(new java.awt.Color(33, 32, 36));
        jPanel50.setForeground(new java.awt.Color(193, 195, 199));
        jPanel50.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel50.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        biayaSks.setForeground(new java.awt.Color(193, 195, 199));
        biayaSks.setText("NIM");
        biayaSks.setPreferredSize(new java.awt.Dimension(200, 29));
        biayaSks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biayaSksMouseClicked(evt);
            }
        });
        jPanel50.add(biayaSks);

        keuanganKuliah.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 247, 218, 29));

        jPanel51.setBackground(new java.awt.Color(33, 32, 36));
        jPanel51.setForeground(new java.awt.Color(193, 195, 199));
        jPanel51.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel51.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        dpp_wajib.setForeground(new java.awt.Color(193, 195, 199));
        dpp_wajib.setText("NIM");
        dpp_wajib.setPreferredSize(new java.awt.Dimension(200, 29));
        dpp_wajib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dpp_wajibMouseClicked(evt);
            }
        });
        jPanel51.add(dpp_wajib);

        keuanganKuliah.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 177, 218, 29));

        jLabel35.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(193, 195, 199));
        jLabel35.setText("Keuangan Kuliah");
        jLabel35.setIconTextGap(0);
        keuanganKuliah.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 48, -1, 38));

        jLabel36.setBackground(new java.awt.Color(33, 32, 36));
        jLabel36.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(193, 195, 199));
        jLabel36.setText("Kewajiban");
        jLabel36.setIconTextGap(0);
        keuanganKuliah.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 153, -1, -1));

        jLabel58.setBackground(new java.awt.Color(33, 32, 36));
        jLabel58.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(193, 195, 199));
        jLabel58.setText("Total Kewajiban");
        jLabel58.setIconTextGap(0);
        keuanganKuliah.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 378, -1, -1));

        jPanel55.setBackground(new java.awt.Color(33, 32, 36));
        jPanel55.setForeground(new java.awt.Color(193, 195, 199));
        jPanel55.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel55.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        totalDenda.setForeground(new java.awt.Color(193, 195, 199));
        totalDenda.setText("NIM");
        totalDenda.setPreferredSize(new java.awt.Dimension(200, 29));
        totalDenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalDendaMouseClicked(evt);
            }
        });
        jPanel55.add(totalDenda);

        keuanganKuliah.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 402, 218, -1));

        jPanel44.setBackground(new java.awt.Color(33, 32, 36));
        jPanel44.setForeground(new java.awt.Color(193, 195, 199));
        jPanel44.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel60.setForeground(new java.awt.Color(193, 195, 199));
        jLabel60.setText("Persentasi Denda (%)");
        jLabel60.setPreferredSize(new java.awt.Dimension(130, 29));
        jPanel44.add(jLabel60);

        keuanganKuliah.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 402, 152, -1));

        hariPerwalian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hariPerwalian.setForeground(new java.awt.Color(102, 102, 102));
        hariPerwalian.setText("hari");
        hariPerwalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hariPerwalianMouseClicked(evt);
            }
        });
        hariPerwalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariPerwalianActionPerformed(evt);
            }
        });
        keuanganKuliah.add(hariPerwalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 304, 50, 30));

        tahunPerwalian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tahunPerwalian.setForeground(new java.awt.Color(102, 102, 102));
        tahunPerwalian.setText("tahun");
        tahunPerwalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tahunPerwalianMouseClicked(evt);
            }
        });
        tahunPerwalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunPerwalianActionPerformed(evt);
            }
        });
        keuanganKuliah.add(tahunPerwalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 304, 50, 30));

        bulanPerwalian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bulanPerwalian.setForeground(new java.awt.Color(102, 102, 102));
        bulanPerwalian.setText("bulan");
        bulanPerwalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bulanPerwalianMouseClicked(evt);
            }
        });
        bulanPerwalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanPerwalianActionPerformed(evt);
            }
        });
        keuanganKuliah.add(bulanPerwalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 304, 50, 30));

        hariPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hariPembayaran.setForeground(new java.awt.Color(102, 102, 102));
        hariPembayaran.setText("hari");
        hariPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hariPembayaranMouseClicked(evt);
            }
        });
        hariPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariPembayaranActionPerformed(evt);
            }
        });
        keuanganKuliah.add(hariPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 344, 50, 30));

        tahunPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tahunPembayaran.setForeground(new java.awt.Color(102, 102, 102));
        tahunPembayaran.setText("tahun");
        tahunPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tahunPembayaranMouseClicked(evt);
            }
        });
        tahunPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunPembayaranActionPerformed(evt);
            }
        });
        keuanganKuliah.add(tahunPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 344, 50, 30));

        bulanPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bulanPembayaran.setForeground(new java.awt.Color(102, 102, 102));
        bulanPembayaran.setText("bulan");
        bulanPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bulanPembayaranMouseClicked(evt);
            }
        });
        bulanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanPembayaranActionPerformed(evt);
            }
        });
        keuanganKuliah.add(bulanPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 344, 50, 30));

        jButton11.setText("Batal");
        jButton11.setPreferredSize(new java.awt.Dimension(30, 30));
        keuanganKuliah.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 60, -1));

        jButton12.setText("Simpan");
        jButton12.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        keuanganKuliah.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 70, -1));

        PanelContent.add(keuanganKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        keuanganKuliah.getAccessibleContext().setAccessibleName("");

        JadwakMahasiswa.setBackground(new java.awt.Color(23, 23, 26));
        JadwakMahasiswa.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel5.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 195, 199));
        jLabel5.setText("Jadwal Perkuliahan");
        jLabel5.setIconTextGap(0);

        jLabel12.setForeground(new java.awt.Color(193, 195, 199));
        jLabel12.setText("Sistem Informasi Akademik");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/w801.png"))); // NOI18N
        jScrollPane3.setViewportView(jLabel13);

        javax.swing.GroupLayout JadwakMahasiswaLayout = new javax.swing.GroupLayout(JadwakMahasiswa);
        JadwakMahasiswa.setLayout(JadwakMahasiswaLayout);
        JadwakMahasiswaLayout.setHorizontalGroup(
            JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        JadwakMahasiswaLayout.setVerticalGroup(
            JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        PanelContent.add(JadwakMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel1.add(PanelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilDataMahasiswa() {
        ControllerAdmin crl = new ControllerAdmin(152021169);
        List<Mahasiswa> listm = crl.getMahasiswa();
        DefaultTableModel model = (DefaultTableModel) daftarMahasiswaTable.getModel();
        model.setRowCount(0);

        for (Mahasiswa m : listm) {
            model.addRow(new Object[]{
                m.getNim(),
                m.getNama(),
                m.getStatus(),
                m.getDosen_wali(),
                m.getSemester_aktif(),
                m.getBatas_studi(),
                m.getEmail(),
                m.getNomor(),
                m.getProdi()
            });
        }
    }

    private void updateData(String field, String value, JLabel target) {
        String message = field;
        String currentName = value;
        boolean confirmed = DarkAlert.showConfirmation(message, currentName);

        if (confirmed) {
            String input = DarkAlert.getTextFieldText();
            if (!input.isEmpty()) {
                target.setText(input);
            } else {
                JOptionPane.showMessageDialog(null, field + " tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private String formatTanggalPerwalian() {
        String hari = hariPerwalian.getText();
        String bulan = bulanPerwalian.getText();
        String tahun = tahunPerwalian.getText();
        String tanggalString = tahun + "-" + bulan + "-" + hari;
        System.out.println("Tanggal yang diinputkan: " + tanggalString);
        return tanggalString;
    }

    private String formatTanggalPembayaran() {
        String hari = hariPerwalian.getText();
        String bulan = bulanPerwalian.getText();
        String tahun = tahunPerwalian.getText();
        String tanggalString = tahun + "-" + bulan + "-" + hari;
        System.out.println("Tanggal yang diinputkan: " + tanggalString);
        return tanggalString;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JadwakMahasiswa.setVisible(false);
        daftarMatakuliah.setVisible(false);
        keuanganKuliah.setVisible(false);
        dashboard.setVisible(false);
        daftarMahasiswa.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JadwakMahasiswa.setVisible(false);
        daftarMatakuliah.setVisible(false);
        keuanganKuliah.setVisible(false);
        daftarMahasiswa.setVisible(false);
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        daftarMahasiswa.setVisible(false);
        dashboard.setVisible(false);
        keuanganKuliah.setVisible(false);
        JadwakMahasiswa.setVisible(false);
        daftarMatakuliah.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        daftarMahasiswa.setVisible(false);
        JadwakMahasiswa.setVisible(false);
        dashboard.setVisible(false);
        daftarMatakuliah.setVisible(false);
        keuanganKuliah.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void tableDark3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDark3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDark3MouseClicked

    private void daftarMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMahasiswaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarMahasiswaMouseClicked

    private void daftarMahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMahasiswaTableMouseClicked
        // TODO add your handling code here:
        int baris = daftarMahasiswaTable.rowAtPoint(evt.getPoint());
        int nim = (int) daftarMahasiswaTable.getValueAt(baris, 0);
        String nama = (String) daftarMahasiswaTable.getValueAt(baris, 1);
        String status = (String) daftarMahasiswaTable.getValueAt(baris, 2);
        String dosen_wali = (String) daftarMahasiswaTable.getValueAt(baris, 3);
        String semester_aktif = (String) daftarMahasiswaTable.getValueAt(baris, 4);
        String batas_studi = (String) daftarMahasiswaTable.getValueAt(baris, 5);
        String email = (String) daftarMahasiswaTable.getValueAt(baris, 6);
        String nomor = (String) daftarMahasiswaTable.getValueAt(baris, 7);
        String prodi = (String) daftarMahasiswaTable.getValueAt(baris, 8);

        this.nim.setText(Integer.toString(nim));
        this.nama.setText(nama);
        this.status.setText(status);
        this.dosenWali.setText(dosen_wali);
        this.semesterAktif.setText(semester_aktif);
        this.batasStudi.setText(batas_studi);
        this.email.setText(email);
        this.nomor.setText(nomor);
        this.programStudi.setText(prodi);
    }//GEN-LAST:event_daftarMahasiswaTableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void dpp_wajibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpp_wajibMouseClicked
        // TODO add your handling code here:
        String field = "dpp_wajib";
        String value = dpp_wajib.getText();
        updateData(field, value, dpp_wajib);
    }//GEN-LAST:event_dpp_wajibMouseClicked

    private void uktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uktMouseClicked
        // TODO add your handling code here:
        String field = "Nama";
        String value = ukt.getText();
        updateData(field, value, ukt);
    }//GEN-LAST:event_uktMouseClicked

    private void biayaSksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biayaSksMouseClicked
        // TODO add your handling code here:
        String field = "Nama";
        String value = biayaSks.getText();
        updateData(field, value, biayaSks);
    }//GEN-LAST:event_biayaSksMouseClicked

    private void totalDendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalDendaMouseClicked
        // TODO add your handling code here:
        String field = "Nama";
        String value = totalDenda.getText();
        updateData(field, value, totalDenda);
    }//GEN-LAST:event_totalDendaMouseClicked

    private void hariPerwalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariPerwalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hariPerwalianActionPerformed

    private void tahunPerwalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunPerwalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunPerwalianActionPerformed

    private void bulanPerwalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanPerwalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanPerwalianActionPerformed

    private void hariPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hariPembayaranActionPerformed

    private void tahunPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunPembayaranActionPerformed

    private void bulanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanPembayaranActionPerformed

    private void hariPerwalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hariPerwalianMouseClicked
        // TODO add your handling code here:
        if (hariPerwalian.getText().equals("hari")) {
            hariPerwalian.setText("");
        }
    }//GEN-LAST:event_hariPerwalianMouseClicked

    private void bulanPerwalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulanPerwalianMouseClicked
        // TODO add your handling code here:
        if (bulanPerwalian.getText().equals("bulan")) {
            bulanPerwalian.setText("");
        }
    }//GEN-LAST:event_bulanPerwalianMouseClicked

    private void tahunPerwalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tahunPerwalianMouseClicked
        // TODO add your handling code here:
        if (tahunPerwalian.getText().equals("tahun")) {
            tahunPerwalian.setText("");
        }
    }//GEN-LAST:event_tahunPerwalianMouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        String dpp_wajib = this.dpp_wajib.getText();
        String ukt = this.ukt.getText();
        String biayaSks = this.biayaSks.getText();
        String tanggalPerwalian = formatTanggalPerwalian();
        String tannggalPembayaran = formatTanggalPembayaran();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        daftarMahasiswa.setVisible(false);
        dashboard.setVisible(false);
        keuanganKuliah.setVisible(false);
        daftarMatakuliah.setVisible(false);
        JadwakMahasiswa.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        ControllerAdmin crl = new ControllerAdmin(152021169);
        Mahasiswa mhs = new Mahasiswa();

        int nim = Integer.parseInt(this.nim.getText());
        String nama = this.nama.getText();
        String status = this.status.getText();
        String dosen_wali = dosenWali.getText();
        String semester_aktif = semesterAktif.getText();
        String batas_studi = batasStudi.getText();
        String email = this.email.getText();
        String nomor = this.nomor.getText();
        String prodi = programStudi.getText();

        mhs.setNim(nim);
        mhs.setNama(nama);
        mhs.setStatus(status);
        mhs.setDosen_wali(dosen_wali);
        mhs.setSemester_aktif(semester_aktif);
        mhs.setBatas_studi(batas_studi);
        mhs.setEmail(email);
        mhs.setNomor(nomor);
        mhs.setProdi(prodi);
        
        crl.tambahMahasiswa(mhs);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        ControllerAdmin crl = new ControllerAdmin(152021169);
        Mahasiswa mhs = new Mahasiswa();

        int nim = Integer.parseInt(this.nim.getText());
        String nama = this.nama.getText();
        String status = this.status.getText();
        String dosen_wali = dosenWali.getText();
        String semester_aktif = semesterAktif.getText();
        String batas_studi = batasStudi.getText();
        String email = this.email.getText();
        String nomor = this.nomor.getText();
        String prodi = programStudi.getText();

        mhs.setNim(nim);
        mhs.setNama(nama);
        mhs.setStatus(status);
        mhs.setDosen_wali(dosen_wali);
        mhs.setSemester_aktif(semester_aktif);
        mhs.setBatas_studi(batas_studi);
        mhs.setEmail(email);
        mhs.setNomor(nomor);
        mhs.setProdi(prodi);
        
        crl.updateMahasiswa(mhs);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        ControllerAdmin crl = new ControllerAdmin(152021169);
        Mahasiswa mhs = new Mahasiswa();

        int nim = Integer.parseInt(this.nim.getText());
        String nama = this.nama.getText();
        String status = this.status.getText();
        String dosen_wali = dosenWali.getText();
        String semester_aktif = semesterAktif.getText();
        String batas_studi = batasStudi.getText();
        String email = this.email.getText();
        String nomor = this.nomor.getText();
        String prodi = programStudi.getText();

        mhs.setNim(nim);
        mhs.setNama(nama);
        mhs.setStatus(status);
        mhs.setDosen_wali(dosen_wali);
        mhs.setSemester_aktif(semester_aktif);
        mhs.setBatas_studi(batas_studi);
        mhs.setEmail(email);
        mhs.setNomor(nomor);
        mhs.setProdi(prodi);
        
        crl.hapusMahasiswa(mhs);
    }//GEN-LAST:event_jButton8MouseClicked

    private void hariPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hariPembayaranMouseClicked
        // TODO add your handling code here:
        if (hariPembayaran.getText().equals("hari")) {
            hariPembayaran.setText("");
        }
    }//GEN-LAST:event_hariPembayaranMouseClicked

    private void bulanPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulanPembayaranMouseClicked
        // TODO add your handling code here:
        if (bulanPembayaran.getText().equals("bulan")) {
            bulanPembayaran.setText("");
        }
    }//GEN-LAST:event_bulanPembayaranMouseClicked

    private void tahunPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tahunPembayaranMouseClicked
        // TODO add your handling code here:
        if (tahunPembayaran.getText().equals("tahun")) {
            tahunPembayaran.setText("");
        }
    }//GEN-LAST:event_tahunPembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JadwakMahasiswa;
    private javax.swing.JPanel PanelContent;
    private javax.swing.JTextField batasStudi;
    private javax.swing.JTextField batasStudi1;
    private javax.swing.JLabel biayaSks;
    private javax.swing.JTextField bulanPembayaran;
    private javax.swing.JTextField bulanPerwalian;
    private javax.swing.JPanel daftarMahasiswa;
    private View.Table.TableDark daftarMahasiswaTable;
    private javax.swing.JPanel daftarMatakuliah;
    private javax.swing.JPanel dashboard;
    private javax.swing.JTextField dosenWali;
    private javax.swing.JTextField dosenWali1;
    private javax.swing.JPanel dpp;
    private javax.swing.JLabel dpp_wajib;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField hariPembayaran;
    private javax.swing.JTextField hariPerwalian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel keuanganKuliah;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField nim1;
    private javax.swing.JTextField nomor;
    private javax.swing.JTextField nomor1;
    private javax.swing.JTextField programStudi;
    private javax.swing.JTextField semesterAktif;
    private javax.swing.JTextField semesterAktif1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField status;
    private javax.swing.JTextField status1;
    private View.Table.TableDark tableDark3;
    private javax.swing.JTextField tahunPembayaran;
    private javax.swing.JTextField tahunPerwalian;
    private javax.swing.JLabel totalDenda;
    private javax.swing.JLabel ukt;
    private javax.swing.JPanel ukt1;
    private javax.swing.JPanel ukv1;
    // End of variables declaration//GEN-END:variables

    public void setAcc(Akun acc) {
        this.acc = acc;
    }
}
