/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControllerAdmin;
import Control.ControllerDosen;
import Control.ControllerMahasiswa;
import javax.swing.JOptionPane;
import Model.Akun;
import Model.Dosen;
import Model.Keuangan;
import Model.Mahasiswa;
import Model.Matakuliah;
import Model.Nilai;
import View.Alert.DarkAlert;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.event.MouseInputListener;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kingt
 */
public class Index_Dosen extends javax.swing.JFrame {

    /**
     * Creates new form Percobaan
     */
    private Akun acc;

    public Index_Dosen() {
        initComponents();
        setupButtonUI();
        refreshData();
        daftarMatakuliahDosen.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        daftarAkun.setVisible(false);
        dataDosen.setVisible(false);
        daftarMatakuliahdosen1.fixTable1(jScrollPane7);
        daftarMatakuliahdosen1.fixTable1(jScrollPane8);
        daftarMatakuliahdosen1.fixTable1(jScrollPane3);
        daftarMatakuliahdosen1.fixTable1(jScrollPane6);
    }

    public Index_Dosen(Akun acc) {
        this.acc = acc;
        initComponents();
        setupButtonUI();
        refreshData();
        daftarMatakuliahDosen.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        daftarAkun.setVisible(false);
        dataDosen.setVisible(false);
        daftarMatakuliahdosen1.fixTable1(jScrollPane7);
        tableDark5.fixTable1(jScrollPane8);
        daftarMatakuliahdosen1.fixTable1(jScrollPane3);
        daftarMatakuliahdosen1.fixTable1(jScrollPane6);
    }

    private void refreshData() {
        tampilDataDosen();
        tampilMatakuliah();
    }

    // Metode untuk mengatur tampilan dan perilaku tombol
    private void setupButtonUI() {
        JButton[] btns = {jButton1, jButton2, jButton3, jButton6};
        for (JButton btn : btns) {
            btn.setBackground(new Color(33, 32, 36));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseInputListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(102, 102, 102));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(33, 32, 36));
                }

                @Override
                public void mouseDragged(MouseEvent e) {
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dataDosen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        nid = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        namaDosen = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        telp = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        alamat = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        prodi = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        daftarMatakuliahDosen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        daftarMatakuliahdosen = new View.Table.TableDark();
        daftarNilaiMatakuliah = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        daftarMatakuliahdosen1 = new View.Table.TableDark();
        jLabel2 = new javax.swing.JLabel();
        JadwakMahasiswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel13 = new javax.swing.JLabel();
        daftarAkun = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDark5 = new View.Table.TableDark();
        jumlahAkun = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        nimAkun = new javax.swing.JTextField();
        jPanel74 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jPanel78 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(33, 32, 36));
        sidePanel.setPreferredSize(new java.awt.Dimension(60, 500));

        jPanel4.setBackground(new java.awt.Color(33, 32, 36));
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 150));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButton6.setBackground(new java.awt.Color(33, 32, 36));
        jButton6.setForeground(new java.awt.Color(50, 98, 227));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_graduation_cap_20px_1.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        sidePanel.add(jPanel4);

        jButton1.setBackground(new java.awt.Color(33, 32, 36));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_registration_20px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(33, 32, 36));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Document_20px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(33, 32, 36));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_event_accepted_tentatively_20px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        sidePanel.add(jButton3);

        jPanel1.add(sidePanel, java.awt.BorderLayout.WEST);

        PanelContent.setMinimumSize(new java.awt.Dimension(0, 0));
        PanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(23, 23, 26));
        dashboard.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel3.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(193, 195, 199));
        jLabel3.setText("Dashboard");
        jLabel3.setIconTextGap(0);

        jLabel4.setForeground(new java.awt.Color(193, 195, 199));
        jLabel4.setText("Sistem Informasi Akademik");

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Varian-Logo-Itenas2-09-768x195.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 195, 199));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_20px.png"))); // NOI18N
        jLabel1.setText("Logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(192, 192, 192))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(160, 160, 160))
        );

        PanelContent.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        dashboard.getAccessibleContext().setAccessibleName("");

        dataDosen.setBackground(new java.awt.Color(23, 23, 26));
        dataDosen.setPreferredSize(new java.awt.Dimension(900, 500));
        dataDosen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(193, 195, 199));
        jLabel11.setText("Data Dosen");
        jLabel11.setIconTextGap(0);
        dataDosen.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 48, -1, 38));

        jLabel17.setForeground(new java.awt.Color(193, 195, 199));
        jLabel17.setText("Sistem Informasi Akademik");
        dataDosen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        jPanel5.setBackground(new java.awt.Color(33, 32, 36));
        jPanel5.setForeground(new java.awt.Color(193, 195, 199));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel18.setForeground(new java.awt.Color(193, 195, 199));
        jLabel18.setText("NID");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 29));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 141, 104, -1));

        jPanel6.setBackground(new java.awt.Color(33, 32, 36));
        jPanel6.setForeground(new java.awt.Color(193, 195, 199));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel19.setForeground(new java.awt.Color(193, 195, 199));
        jLabel19.setText("Nomor Telp");
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 29));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 213, 104, -1));

        jPanel7.setBackground(new java.awt.Color(33, 32, 36));
        jPanel7.setForeground(new java.awt.Color(193, 195, 199));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel20.setForeground(new java.awt.Color(193, 195, 199));
        jLabel20.setText("Email");
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 29));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 249, 104, -1));

        jPanel11.setBackground(new java.awt.Color(33, 32, 36));
        jPanel11.setForeground(new java.awt.Color(193, 195, 199));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel21.setForeground(new java.awt.Color(193, 195, 199));
        jLabel21.setText("Nama Dosen");
        jLabel21.setPreferredSize(new java.awt.Dimension(90, 29));

        jPanel26.setBackground(new java.awt.Color(33, 32, 36));
        jPanel26.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel39.setText("Nama Mahasiswa");
        jLabel39.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel26.add(jLabel39);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataDosen.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 177, 104, -1));

        jPanel12.setBackground(new java.awt.Color(33, 32, 36));
        jPanel12.setForeground(new java.awt.Color(193, 195, 199));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel22.setForeground(new java.awt.Color(193, 195, 199));
        jLabel22.setText("Alamat");
        jLabel22.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 104, -1));

        jPanel16.setBackground(new java.awt.Color(33, 32, 36));
        jPanel16.setForeground(new java.awt.Color(193, 195, 199));
        jPanel16.setPreferredSize(new java.awt.Dimension(100, 30));

        nid.setForeground(new java.awt.Color(193, 195, 199));
        nid.setText("NIM");
        nid.setPreferredSize(new java.awt.Dimension(600, 29));
        nid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nidMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 141, 640, -1));

        jPanel17.setBackground(new java.awt.Color(33, 32, 36));
        jPanel17.setForeground(new java.awt.Color(193, 195, 199));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 30));

        namaDosen.setForeground(new java.awt.Color(193, 195, 199));
        namaDosen.setText("NIM");
        namaDosen.setPreferredSize(new java.awt.Dimension(600, 29));
        namaDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaDosenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(namaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 177, 640, -1));

        jPanel18.setBackground(new java.awt.Color(33, 32, 36));
        jPanel18.setForeground(new java.awt.Color(193, 195, 199));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 30));

        telp.setForeground(new java.awt.Color(193, 195, 199));
        telp.setText("NIM");
        telp.setPreferredSize(new java.awt.Dimension(600, 29));
        telp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 213, 640, -1));

        jPanel19.setBackground(new java.awt.Color(33, 32, 36));
        jPanel19.setForeground(new java.awt.Color(193, 195, 199));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 30));

        email.setForeground(new java.awt.Color(193, 195, 199));
        email.setText("NIM");
        email.setPreferredSize(new java.awt.Dimension(600, 29));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 249, 640, -1));

        jPanel20.setBackground(new java.awt.Color(33, 32, 36));
        jPanel20.setForeground(new java.awt.Color(193, 195, 199));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 30));

        alamat.setForeground(new java.awt.Color(193, 195, 199));
        alamat.setText("NIM");
        alamat.setPreferredSize(new java.awt.Dimension(600, 29));
        alamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alamatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 285, 640, -1));

        jPanel22.setBackground(new java.awt.Color(33, 32, 36));
        jPanel22.setForeground(new java.awt.Color(193, 195, 199));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 30));

        prodi.setForeground(new java.awt.Color(193, 195, 199));
        prodi.setText("NIM");
        prodi.setPreferredSize(new java.awt.Dimension(600, 29));
        prodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 321, 640, -1));

        jPanel13.setBackground(new java.awt.Color(33, 32, 36));
        jPanel13.setForeground(new java.awt.Color(193, 195, 199));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel25.setForeground(new java.awt.Color(193, 195, 199));
        jLabel25.setText("Program Studi");
        jLabel25.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataDosen.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 321, 104, -1));

        PanelContent.add(dataDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        daftarMatakuliahDosen.setBackground(new java.awt.Color(23, 23, 26));
        daftarMatakuliahDosen.setPreferredSize(new java.awt.Dimension(900, 500));
        daftarMatakuliahDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMatakuliahDosenMouseClicked(evt);
            }
        });
        daftarMatakuliahDosen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(193, 195, 199));
        jLabel9.setText("Daftar Matakuliah");
        jLabel9.setIconTextGap(0);
        daftarMatakuliahDosen.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 48, -1, 38));

        jLabel10.setForeground(new java.awt.Color(193, 195, 199));
        jLabel10.setText("Sistem Informasi Akademik");
        daftarMatakuliahDosen.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        daftarMatakuliahdosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Matakuliah", "SKS", "Kelas", "Jenis"
            }
        ));
        daftarMatakuliahdosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMatakuliahdosenMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(daftarMatakuliahdosen);

        daftarMatakuliahDosen.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 670, 350));

        PanelContent.add(daftarMatakuliahDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));
        daftarMatakuliahDosen.getAccessibleContext().setAccessibleName("");

        daftarNilaiMatakuliah.setBackground(new java.awt.Color(23, 23, 26));
        daftarNilaiMatakuliah.setPreferredSize(new java.awt.Dimension(900, 500));
        daftarNilaiMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarNilaiMatakuliahMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(193, 195, 199));
        jLabel14.setText("Daftar Nilai Mahasiswa");
        jLabel14.setIconTextGap(0);

        jLabel15.setForeground(new java.awt.Color(193, 195, 199));
        jLabel15.setText("Sistem Informasi Akademik");

        jScrollPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane8MouseClicked(evt);
            }
        });

        daftarMatakuliahdosen1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nim", "Kode", "Matakuliah", "SKS", "Semester", "Nilai", "Bobot", "NxK"
            }
        ));
        daftarMatakuliahdosen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMatakuliahdosen1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daftarMatakuliahdosen1MouseEntered(evt);
            }
        });
        jScrollPane8.setViewportView(daftarMatakuliahdosen1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 195, 199));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_back_20px.png"))); // NOI18N
        jLabel2.setText("BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout daftarNilaiMatakuliahLayout = new javax.swing.GroupLayout(daftarNilaiMatakuliah);
        daftarNilaiMatakuliah.setLayout(daftarNilaiMatakuliahLayout);
        daftarNilaiMatakuliahLayout.setHorizontalGroup(
            daftarNilaiMatakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarNilaiMatakuliahLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(daftarNilaiMatakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(daftarNilaiMatakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(daftarNilaiMatakuliahLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        daftarNilaiMatakuliahLayout.setVerticalGroup(
            daftarNilaiMatakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarNilaiMatakuliahLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(daftarNilaiMatakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addComponent(jLabel15)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelContent.add(daftarNilaiMatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        JadwakMahasiswa.setBackground(new java.awt.Color(23, 23, 26));
        JadwakMahasiswa.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel5.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 195, 199));
        jLabel5.setText("Jadwal Perkuliahan");
        jLabel5.setIconTextGap(0);

        jLabel12.setForeground(new java.awt.Color(193, 195, 199));
        jLabel12.setText("Sistem Informasi Akademik");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/w801.png"))); // NOI18N
        jScrollPane3.setViewportView(jLabel13);

        javax.swing.GroupLayout JadwakMahasiswaLayout = new javax.swing.GroupLayout(JadwakMahasiswa);
        JadwakMahasiswa.setLayout(JadwakMahasiswaLayout);
        JadwakMahasiswaLayout.setHorizontalGroup(
            JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        JadwakMahasiswaLayout.setVerticalGroup(
            JadwakMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JadwakMahasiswaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        PanelContent.add(JadwakMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        daftarAkun.setBackground(new java.awt.Color(23, 23, 26));
        daftarAkun.setPreferredSize(new java.awt.Dimension(900, 500));
        daftarAkun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(193, 195, 199));
        jLabel48.setText("Daftar Akun");
        jLabel48.setIconTextGap(0);
        daftarAkun.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 48, -1, 38));

        jLabel49.setForeground(new java.awt.Color(193, 195, 199));
        jLabel49.setText("Sistem Informasi Akademik");
        daftarAkun.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, -1, -1));

        tableDark5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nim", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDark5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDark5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableDark5);

        daftarAkun.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 199, 400, 120));

        jumlahAkun.setForeground(new java.awt.Color(193, 195, 199));
        jumlahAkun.setText("jLabel6");
        daftarAkun.add(jumlahAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 165, 80, -1));

        jLabel51.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(193, 195, 199));
        jLabel51.setText("Jumlah Akun :");
        daftarAkun.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, -1, -1));

        jPanel14.setBackground(new java.awt.Color(33, 32, 36));
        jPanel14.setForeground(new java.awt.Color(193, 195, 199));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(new java.awt.Color(193, 195, 199));
        jLabel23.setText("Username");
        jLabel23.setPreferredSize(new java.awt.Dimension(80, 29));
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        daftarAkun.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 104, -1));

        jPanel15.setBackground(new java.awt.Color(33, 32, 36));
        jPanel15.setForeground(new java.awt.Color(193, 195, 199));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setForeground(new java.awt.Color(193, 195, 199));
        jLabel24.setText("Nim");
        jLabel24.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 90, -1));

        daftarAkun.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 104, -1));

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        daftarAkun.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 290, 30));

        nimAkun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nimAkun.setForeground(new java.awt.Color(102, 102, 102));
        daftarAkun.add(nimAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 290, 30));

        jPanel74.setBackground(new java.awt.Color(33, 32, 36));
        jPanel74.setForeground(new java.awt.Color(193, 195, 199));
        jPanel74.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel93.setForeground(new java.awt.Color(193, 195, 199));
        jLabel93.setText("Password");
        jLabel93.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel74.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jPanel78.setBackground(new java.awt.Color(33, 32, 36));
        jPanel78.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel78.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel97.setText("Nama Mahasiswa");
        jLabel97.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel78.add(jLabel97);

        jPanel74.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        daftarAkun.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 104, -1));

        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        daftarAkun.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 290, 30));

        jButton16.setForeground(new java.awt.Color(193, 195, 199));
        jButton16.setText("Update");
        jButton16.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        daftarAkun.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 110, -1));

        PanelContent.add(daftarAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel1.add(PanelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilMahasiswa() {
        ControllerDosen crl = new ControllerDosen();
        List<Mahasiswa> listmhs = crl.getMhs();
        DefaultTableModel model = (DefaultTableModel) daftarMatakuliahdosen.getModel();
        model.setRowCount(0);

        for (Mahasiswa mhs : listmhs) {
            model.addRow(new Object[]{
                mhs.getNim(),
                mhs.getNama(),
                mhs.getStatus(),
                mhs.getDosen_wali(),
                mhs.getSemester_aktif(),
                mhs.getBatas_studi(),
                mhs.getEmail(),
                mhs.getNomor(),
                mhs.getProdi()
            });
        }
    }

    private void tampilMatakuliah() {
        ControllerDosen crl = new ControllerDosen();
        List<Matakuliah> listMk = crl.getMatakuliah();
        DefaultTableModel model = (DefaultTableModel) daftarMatakuliahdosen.getModel();
        model.setRowCount(0);

        for (Matakuliah n : listMk) {
            model.addRow(new Object[]{
                n.getKode(),
                n.getMatakuliah(),
                n.getSks(),
                n.getKelas(),
                n.getJenis()
            });
        }
    }

    private void tampilNilai(String kode) {
        ControllerDosen crl = new ControllerDosen();
        List<Nilai> listn = crl.getNilai(kode);
        DefaultTableModel model = (DefaultTableModel) daftarMatakuliahdosen1.getModel();
        model.setRowCount(0);

        for (Nilai n : listn) {
            model.addRow(new Object[]{
                n.getNim(),
                n.getKode(),
                n.getMataKuliah(),
                n.getSks(),
                n.getSemester(),
                n.getNilai(),
                n.getBobot(),
                n.getNk()
            });
        }
    }

    private void updateNilai(int nim, String kode, String nilai, int sks) {
        ControllerDosen crl = new ControllerDosen();
        crl.updateNilai(nim, kode, nilai, sks);
    }

    private void tampilDataDosen() {
        ControllerDosen crl = new ControllerDosen(acc);
        Dosen ds = crl.getDosen();
        nid.setText(Integer.toString(ds.getNid()));
        namaDosen.setText(ds.getNama());
        telp.setText(ds.getNomor());
        email.setText(ds.getEmail());
        alamat.setText(ds.getAlamat());
        prodi.setText(ds.getProdi());
    }

    private void updateData(String field, String value) {
        String message = field;
        String currentName = value;
        boolean confirmed = DarkAlert.showConfirmation(message, currentName);

        if (confirmed) {
            String input = DarkAlert.getTextFieldText();
            if (!input.isEmpty()) {
                ControllerDosen crl = new ControllerDosen(acc);
                crl.updateDataDosen(field.toLowerCase(), input);
                tampilDataDosen();
                JOptionPane.showMessageDialog(null, field + " berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, field + " tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JadwakMahasiswa.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        daftarAkun.setVisible(false);
        dashboard.setVisible(false);
        daftarMatakuliahDosen.setVisible(false);
        dataDosen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JadwakMahasiswa.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        daftarMatakuliahDosen.setVisible(false);
        daftarAkun.setVisible(false);
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dashboard.setVisible(false);
        daftarAkun.setVisible(false);
        JadwakMahasiswa.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        dataDosen.setVisible(false);
        daftarMatakuliahDosen.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void daftarMatakuliahDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMatakuliahDosenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarMatakuliahDosenMouseClicked

    private void daftarMatakuliahdosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMatakuliahdosenMouseClicked
        // TODO add your handling code here:        
        int baris = daftarMatakuliahdosen.rowAtPoint(evt.getPoint());
        var confirmed = DarkAlert.showConfirmation("Lihat Nilai Mahasiswa?", (String) daftarMatakuliahdosen.getValueAt(baris, 1));
        String kode = (String) daftarMatakuliahdosen.getValueAt(baris, 0);
        if (confirmed) {
            tampilNilai(kode);
            daftarMatakuliahDosen.setVisible(false);
            daftarNilaiMatakuliah.setVisible(true);
            refreshData();
        }
    }//GEN-LAST:event_daftarMatakuliahdosenMouseClicked

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        daftarMatakuliahDosen.setVisible(false);
        dashboard.setVisible(false);
        daftarNilaiMatakuliah.setVisible(false);
        daftarAkun.setVisible(false);
        JadwakMahasiswa.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void daftarNilaiMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarNilaiMatakuliahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNilaiMatakuliahMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void daftarMatakuliahdosen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMatakuliahdosen1MouseClicked
        // TODO add your handling code here:
        int baris = daftarMatakuliahdosen1.rowAtPoint(evt.getPoint());
        var confirmed = DarkAlert.showConfirmation("Ubah Nilai?", (String) daftarMatakuliahdosen1.getValueAt(baris, 5));
        if (confirmed) {
            int nim = (int) daftarMatakuliahdosen1.getValueAt(baris, 0);
            String kode = (String) daftarMatakuliahdosen1.getValueAt(baris, 1);
            String sks = (String) daftarMatakuliahdosen1.getValueAt(baris, 3);
            int intSks = Integer.parseInt(sks);
            String nilai = DarkAlert.getTextFieldText();
            updateNilai(nim, kode, nilai, intSks);
            tampilNilai(kode);
            refreshData();
        }
    }//GEN-LAST:event_daftarMatakuliahdosen1MouseClicked

    private void daftarMatakuliahdosen1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMatakuliahdosen1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarMatakuliahdosen1MouseEntered

    private void jScrollPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane8MouseClicked

    private void nidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nidMouseClicked

    private void namaDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaDosenMouseClicked
        // TODO add your handling code here:
        String field = "Nama";
        String value = namaDosen.getText();
        updateData(field, value);
    }//GEN-LAST:event_namaDosenMouseClicked

    private void telpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telpMouseClicked
        // TODO add your handling code here:
        String field = "Nomor";
        String value = telp.getText();
        updateData(field, value);
    }//GEN-LAST:event_telpMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        String field = "Email";
        String value = email.getText();
        updateData(field, value);
    }//GEN-LAST:event_emailMouseClicked

    private void alamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alamatMouseClicked
        // TODO add your handling code here:
        String field = "Alamat";
        String value = alamat.getText();
        updateData(field, value);
    }//GEN-LAST:event_alamatMouseClicked

    private void prodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiMouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        ControllerAdmin crl = new ControllerAdmin(acc);
        Akun acc = new Akun();
        int nim = Integer.parseInt(nimAkun.getText());
        String username = this.username.getText();
        String password = this.password.getText();
        acc.setUsername(username);
        acc.setPassword(password);
        crl.updateAkun(acc, nim);
        refreshData();
    }//GEN-LAST:event_jButton16MouseClicked

    private void tableDark5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDark5MouseClicked
        // TODO add your handling code here:
        int baris = daftarMatakuliahdosen.rowAtPoint(evt.getPoint());
        var confirmed = DarkAlert.showConfirmation("Ubah Nilai?", (String) daftarMatakuliahdosen.getValueAt(baris, 5));
        String nilai = (String) daftarMatakuliahdosen.getValueAt(baris, 5);
        if (confirmed) {
            refreshData();
        }
    }//GEN-LAST:event_tableDark5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        daftarNilaiMatakuliah.setVisible(false);
        daftarMatakuliahDosen.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index_Dosen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index_Dosen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index_Dosen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index_Dosen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JadwakMahasiswa;
    private javax.swing.JPanel PanelContent;
    private javax.swing.JLabel alamat;
    private javax.swing.JPanel daftarAkun;
    private javax.swing.JPanel daftarMatakuliahDosen;
    private View.Table.TableDark daftarMatakuliahdosen;
    private View.Table.TableDark daftarMatakuliahdosen1;
    private javax.swing.JPanel daftarNilaiMatakuliah;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dataDosen;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel jumlahAkun;
    private javax.swing.JLabel namaDosen;
    private javax.swing.JLabel nid;
    private javax.swing.JTextField nimAkun;
    private javax.swing.JTextField password;
    private javax.swing.JLabel prodi;
    private javax.swing.JPanel sidePanel;
    private View.Table.TableDark tableDark5;
    private javax.swing.JLabel telp;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public void setAcc(Akun acc) {
        this.acc = acc;
    }
}
