/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControllerMahasiswa;
import Model.Keuangan;
import Model.Mahasiswa;
import Model.Nilai;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.event.MouseInputListener;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author kingt
 */
public class Percobaan extends javax.swing.JFrame {

    /**
     * Creates new form Percobaan
     */
    public Percobaan() {
        initComponents();
        tableDark1.fixTable(jScrollPane1);
        dashboard.setVisible(true);
        dataMahasiswa.setVisible(false);
        nilaiMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        JButton[] btns = {jButton1, jButton2, jButton3, jButton4, jButton6};
        for (JButton btn : btns) {
            btn.setBackground(new Color(33, 32, 36));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseInputListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(102, 102, 102));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(16, 15, 15));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(33, 32, 36));
                }

                @Override
                public void mouseDragged(MouseEvent e) {
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();
        nilaiMahasiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new View.TableDark();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataMahasiswa = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        keuanganKuliah = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ukt1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        ukv1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        dpp = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        ukt = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        ukv = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        dpp_wajib = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        telat_perwalian = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        telat_pembayaran = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(33, 32, 36));
        sidePanel.setPreferredSize(new java.awt.Dimension(60, 500));

        jPanel4.setBackground(new java.awt.Color(33, 32, 36));
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 150));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButton6.setBackground(new java.awt.Color(33, 32, 36));
        jButton6.setForeground(new java.awt.Color(50, 98, 227));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_home_20px_4.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        sidePanel.add(jPanel4);

        jButton1.setBackground(new java.awt.Color(33, 32, 36));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_registration_20px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(33, 32, 36));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Document_20px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(33, 32, 36));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_event_accepted_tentatively_20px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        sidePanel.add(jButton3);

        jButton4.setBackground(new java.awt.Color(33, 32, 36));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_online_payment_20px_4.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton4);

        jPanel1.add(sidePanel, java.awt.BorderLayout.WEST);

        PanelContent.setMinimumSize(new java.awt.Dimension(0, 0));
        PanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nilaiMahasiswa.setBackground(new java.awt.Color(23, 23, 26));
        nilaiMahasiswa.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 195, 199));
        jLabel1.setText("Nilai Mahasiswa");
        jLabel1.setIconTextGap(0);

        jLabel2.setForeground(new java.awt.Color(193, 195, 199));
        jLabel2.setText("Sistem Informasi Akademik");

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableDark1);

        jLabel6.setForeground(new java.awt.Color(193, 195, 199));
        jLabel6.setText("jLabel6");

        jLabel11.setForeground(new java.awt.Color(193, 195, 199));
        jLabel11.setText("N.I.M : ");

        jLabel8.setForeground(new java.awt.Color(193, 195, 199));
        jLabel8.setText("jLabel8");

        jLabel7.setForeground(new java.awt.Color(193, 195, 199));
        jLabel7.setText("Wali Dosen : ");

        javax.swing.GroupLayout nilaiMahasiswaLayout = new javax.swing.GroupLayout(nilaiMahasiswa);
        nilaiMahasiswa.setLayout(nilaiMahasiswaLayout);
        nilaiMahasiswaLayout.setHorizontalGroup(
            nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nilaiMahasiswaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(nilaiMahasiswaLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGroup(nilaiMahasiswaLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel8))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        nilaiMahasiswaLayout.setVerticalGroup(
            nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nilaiMahasiswaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(nilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        PanelContent.add(nilaiMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        nilaiMahasiswa.getAccessibleContext().setAccessibleName("");

        dataMahasiswa.setBackground(new java.awt.Color(23, 23, 26));
        dataMahasiswa.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel9.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(193, 195, 199));
        jLabel9.setText("Data Mahasiswa");
        jLabel9.setIconTextGap(0);

        jLabel10.setForeground(new java.awt.Color(193, 195, 199));
        jLabel10.setText("Sistem Informasi Akademik");

        jPanel5.setBackground(new java.awt.Color(33, 32, 36));
        jPanel5.setForeground(new java.awt.Color(193, 195, 199));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel17.setForeground(new java.awt.Color(193, 195, 199));
        jLabel17.setText("NIM");
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 29));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(33, 32, 36));
        jPanel6.setForeground(new java.awt.Color(193, 195, 199));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel18.setForeground(new java.awt.Color(193, 195, 199));
        jLabel18.setText("Status");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 29));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBackground(new java.awt.Color(33, 32, 36));
        jPanel7.setForeground(new java.awt.Color(193, 195, 199));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel19.setForeground(new java.awt.Color(193, 195, 199));
        jLabel19.setText("Dosen Wali");
        jLabel19.setPreferredSize(new java.awt.Dimension(80, 29));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel11.setBackground(new java.awt.Color(33, 32, 36));
        jPanel11.setForeground(new java.awt.Color(193, 195, 199));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel20.setForeground(new java.awt.Color(193, 195, 199));
        jLabel20.setText("Nama Mahasiswa");
        jLabel20.setPreferredSize(new java.awt.Dimension(90, 29));

        jPanel26.setBackground(new java.awt.Color(33, 32, 36));
        jPanel26.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel39.setText("Nama Mahasiswa");
        jLabel39.setPreferredSize(new java.awt.Dimension(90, 29));
        jPanel26.add(jLabel39);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(33, 32, 36));
        jPanel12.setForeground(new java.awt.Color(193, 195, 199));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel21.setForeground(new java.awt.Color(193, 195, 199));
        jLabel21.setText("Semester Aktif");
        jLabel21.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel13.setBackground(new java.awt.Color(33, 32, 36));
        jPanel13.setForeground(new java.awt.Color(193, 195, 199));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel22.setForeground(new java.awt.Color(193, 195, 199));
        jLabel22.setText("Batas Studi");
        jLabel22.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel27.setBackground(new java.awt.Color(33, 32, 36));
        jPanel27.setForeground(new java.awt.Color(193, 195, 199));
        jPanel27.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel40.setForeground(new java.awt.Color(193, 195, 199));
        jLabel40.setText("Email");
        jLabel40.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel28.setBackground(new java.awt.Color(33, 32, 36));
        jPanel28.setForeground(new java.awt.Color(193, 195, 199));
        jPanel28.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel41.setForeground(new java.awt.Color(193, 195, 199));
        jLabel41.setText("No. HP");
        jLabel41.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel29.setBackground(new java.awt.Color(33, 32, 36));
        jPanel29.setForeground(new java.awt.Color(193, 195, 199));
        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel42.setForeground(new java.awt.Color(193, 195, 199));
        jLabel42.setText("Program Studi");
        jLabel42.setPreferredSize(new java.awt.Dimension(95, 29));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel14.setBackground(new java.awt.Color(33, 32, 36));
        jPanel14.setForeground(new java.awt.Color(193, 195, 199));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel23.setForeground(new java.awt.Color(193, 195, 199));
        jLabel23.setText("NIM");
        jLabel23.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel15.setBackground(new java.awt.Color(33, 32, 36));
        jPanel15.setForeground(new java.awt.Color(193, 195, 199));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel24.setForeground(new java.awt.Color(193, 195, 199));
        jLabel24.setText("NIM");
        jLabel24.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel16.setBackground(new java.awt.Color(33, 32, 36));
        jPanel16.setForeground(new java.awt.Color(193, 195, 199));
        jPanel16.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel25.setForeground(new java.awt.Color(193, 195, 199));
        jLabel25.setText("NIM");
        jLabel25.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel17.setBackground(new java.awt.Color(33, 32, 36));
        jPanel17.setForeground(new java.awt.Color(193, 195, 199));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel26.setForeground(new java.awt.Color(193, 195, 199));
        jLabel26.setText("NIM");
        jLabel26.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel18.setBackground(new java.awt.Color(33, 32, 36));
        jPanel18.setForeground(new java.awt.Color(193, 195, 199));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel27.setForeground(new java.awt.Color(193, 195, 199));
        jLabel27.setText("NIM");
        jLabel27.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel19.setBackground(new java.awt.Color(33, 32, 36));
        jPanel19.setForeground(new java.awt.Color(193, 195, 199));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel28.setForeground(new java.awt.Color(193, 195, 199));
        jLabel28.setText("NIM");
        jLabel28.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel20.setBackground(new java.awt.Color(33, 32, 36));
        jPanel20.setForeground(new java.awt.Color(193, 195, 199));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel29.setForeground(new java.awt.Color(193, 195, 199));
        jLabel29.setText("NIM");
        jLabel29.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel21.setBackground(new java.awt.Color(33, 32, 36));
        jPanel21.setForeground(new java.awt.Color(193, 195, 199));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel30.setForeground(new java.awt.Color(193, 195, 199));
        jLabel30.setText("NIM");
        jLabel30.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel22.setBackground(new java.awt.Color(33, 32, 36));
        jPanel22.setForeground(new java.awt.Color(193, 195, 199));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel31.setForeground(new java.awt.Color(193, 195, 199));
        jLabel31.setText("NIM");
        jLabel31.setPreferredSize(new java.awt.Dimension(600, 29));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dataMahasiswaLayout = new javax.swing.GroupLayout(dataMahasiswa);
        dataMahasiswa.setLayout(dataMahasiswaLayout);
        dataMahasiswaLayout.setHorizontalGroup(
            dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(dataMahasiswaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        dataMahasiswaLayout.setVerticalGroup(
            dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataMahasiswaLayout.createSequentialGroup()
                        .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dataMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        PanelContent.add(dataMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));
        dataMahasiswa.getAccessibleContext().setAccessibleName("");

        keuanganKuliah.setBackground(new java.awt.Color(23, 23, 26));
        keuanganKuliah.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel16.setBackground(new java.awt.Color(33, 32, 36));
        jLabel16.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(193, 195, 199));
        jLabel16.setText("Denda");
        jLabel16.setIconTextGap(0);

        jLabel37.setForeground(new java.awt.Color(193, 195, 199));
        jLabel37.setText("Sistem Informasi Akademik");

        ukt1.setBackground(new java.awt.Color(33, 32, 36));
        ukt1.setForeground(new java.awt.Color(193, 195, 199));
        ukt1.setMinimumSize(new java.awt.Dimension(30, 15));
        ukt1.setPreferredSize(new java.awt.Dimension(120, 29));
        ukt1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel43.setForeground(new java.awt.Color(193, 195, 199));
        jLabel43.setText("UKT (Uang Kuliah Tetap)");
        jLabel43.setPreferredSize(new java.awt.Dimension(130, 29));
        ukt1.add(jLabel43);

        ukv1.setBackground(new java.awt.Color(33, 32, 36));
        ukv1.setForeground(new java.awt.Color(193, 195, 199));
        ukv1.setMinimumSize(new java.awt.Dimension(32, 15));
        ukv1.setPreferredSize(new java.awt.Dimension(120, 29));
        ukv1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel44.setForeground(new java.awt.Color(193, 195, 199));
        jLabel44.setText("UKV (Uang Kuliah Variabel)");
        jLabel44.setPreferredSize(new java.awt.Dimension(140, 29));
        ukv1.add(jLabel44);

        dpp.setBackground(new java.awt.Color(33, 32, 36));
        dpp.setForeground(new java.awt.Color(193, 195, 199));
        dpp.setMinimumSize(new java.awt.Dimension(58, 15));
        dpp.setPreferredSize(new java.awt.Dimension(120, 29));
        dpp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel46.setForeground(new java.awt.Color(193, 195, 199));
        jLabel46.setText("DPP Wajib");
        jLabel46.setPreferredSize(new java.awt.Dimension(130, 29));
        dpp.add(jLabel46);

        jPanel42.setBackground(new java.awt.Color(33, 32, 36));
        jPanel42.setForeground(new java.awt.Color(193, 195, 199));
        jPanel42.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel54.setForeground(new java.awt.Color(193, 195, 199));
        jLabel54.setText("Telat Perwalian");
        jLabel54.setPreferredSize(new java.awt.Dimension(130, 29));
        jPanel42.add(jLabel54);

        jPanel45.setBackground(new java.awt.Color(33, 32, 36));
        jPanel45.setForeground(new java.awt.Color(193, 195, 199));
        jPanel45.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel45.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel55.setForeground(new java.awt.Color(193, 195, 199));
        jLabel55.setText("Telat Pembayaran");
        jLabel55.setPreferredSize(new java.awt.Dimension(130, 29));
        jPanel45.add(jLabel55);

        jPanel49.setBackground(new java.awt.Color(33, 32, 36));
        jPanel49.setForeground(new java.awt.Color(193, 195, 199));
        jPanel49.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel49.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        ukt.setForeground(new java.awt.Color(193, 195, 199));
        ukt.setText("NIM");
        ukt.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel49.add(ukt);

        jPanel50.setBackground(new java.awt.Color(33, 32, 36));
        jPanel50.setForeground(new java.awt.Color(193, 195, 199));
        jPanel50.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel50.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        ukv.setForeground(new java.awt.Color(193, 195, 199));
        ukv.setText("NIM");
        ukv.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel50.add(ukv);

        jPanel51.setBackground(new java.awt.Color(33, 32, 36));
        jPanel51.setForeground(new java.awt.Color(193, 195, 199));
        jPanel51.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel51.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        dpp_wajib.setForeground(new java.awt.Color(193, 195, 199));
        dpp_wajib.setText("NIM");
        dpp_wajib.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel51.add(dpp_wajib);

        jPanel52.setBackground(new java.awt.Color(33, 32, 36));
        jPanel52.setForeground(new java.awt.Color(193, 195, 199));
        jPanel52.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel52.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        telat_perwalian.setForeground(new java.awt.Color(193, 195, 199));
        telat_perwalian.setText("NIM");
        telat_perwalian.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel52.add(telat_perwalian);

        jPanel53.setBackground(new java.awt.Color(33, 32, 36));
        jPanel53.setForeground(new java.awt.Color(193, 195, 199));
        jPanel53.setPreferredSize(new java.awt.Dimension(630, 30));
        jPanel53.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        telat_pembayaran.setForeground(new java.awt.Color(193, 195, 199));
        telat_pembayaran.setText("NIM");
        telat_pembayaran.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel53.add(telat_pembayaran);

        jLabel35.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(193, 195, 199));
        jLabel35.setText("Keuangan Kuliah");
        jLabel35.setIconTextGap(0);

        jLabel36.setBackground(new java.awt.Color(33, 32, 36));
        jLabel36.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(193, 195, 199));
        jLabel36.setText("Kewajiban");
        jLabel36.setIconTextGap(0);

        jLabel38.setBackground(new java.awt.Color(33, 32, 36));
        jLabel38.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(193, 195, 199));
        jLabel38.setText("VA (Virtual Account)");
        jLabel38.setIconTextGap(0);

        jPanel43.setBackground(new java.awt.Color(33, 32, 36));
        jPanel43.setForeground(new java.awt.Color(193, 195, 199));
        jPanel43.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel43.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel69.setPreferredSize(new java.awt.Dimension(95, 29));
        jPanel43.add(jLabel69);

        javax.swing.GroupLayout keuanganKuliahLayout = new javax.swing.GroupLayout(keuanganKuliah);
        keuanganKuliah.setLayout(keuanganKuliahLayout);
        keuanganKuliahLayout.setHorizontalGroup(
            keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keuanganKuliahLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel38)
                        .addComponent(jLabel36)
                        .addComponent(jLabel16)
                        .addGroup(keuanganKuliahLayout.createSequentialGroup()
                            .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addComponent(jLabel37)
                        .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keuanganKuliahLayout.createSequentialGroup()
                            .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ukt1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(ukv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(6, 6, 6)
                            .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        keuanganKuliahLayout.setVerticalGroup(
            keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keuanganKuliahLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ukt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ukv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keuanganKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(keuanganKuliahLayout.createSequentialGroup()
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(keuanganKuliahLayout.createSequentialGroup()
                        .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        PanelContent.add(keuanganKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        keuanganKuliah.getAccessibleContext().setAccessibleName("");

        dashboard.setBackground(new java.awt.Color(23, 23, 26));
        dashboard.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel3.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(193, 195, 199));
        jLabel3.setText("Dashboard");
        jLabel3.setIconTextGap(0);

        jLabel4.setForeground(new java.awt.Color(193, 195, 199));
        jLabel4.setText("Sistem Informasi Akademik");

        jPanel8.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(33, 32, 36));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(dashboardLayout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        PanelContent.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        dashboard.getAccessibleContext().setAccessibleName("");

        jPanel1.add(PanelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilNilai() {
        ControllerMahasiswa crl = new ControllerMahasiswa(152021169);
        List<Nilai> listn = crl.getNilai();
        DefaultTableModel model = (DefaultTableModel) tableDark1.getModel();
        model.setRowCount(0);

        model.addColumn("ID");
        model.addColumn("Kode");
        model.addColumn("Mata Kuliah");
        model.addColumn("SKS");
        model.addColumn("Semester");
        model.addColumn("Nilai");
        model.addColumn("Bobot");
        model.addColumn("NxK");

        for (Nilai n : listn) {
            model.addRow(new Object[]{
                n.getId(),
                n.getKode(),
                n.getMataKuliah(),
                n.getSks(),
                n.getSemester(),
                n.getNilai(),
                n.getBobot(),
                n.getNk()
            });
        }

    }

    private void tampilDataMahasiswa() {
        ControllerMahasiswa crl = new ControllerMahasiswa(152021169);
        Mahasiswa mhs = crl.getMhs();
        jLabel23.setText(Integer.toString(mhs.getNim()));
        jLabel24.setText(mhs.getNama());
        jLabel25.setText(mhs.getStatus());
        jLabel26.setText(mhs.getDosen_wali());
        jLabel27.setText(mhs.getSemester_aktif());
        jLabel28.setText(mhs.getBatas_studi());
        jLabel29.setText(mhs.getEmail());
        jLabel30.setText(mhs.getNomor());
        jLabel31.setText(mhs.getProdi());
    }

    private void tampilKeuangan() {
        ControllerMahasiswa crl = new ControllerMahasiswa(152021169);
        Keuangan ku = crl.getKeuangan();
        dpp_wajib.setText(Double.toString(ku.getDpp_wajib()));
        ukt.setText(Double.toString(ku.getUkt()));
        ukv.setText(Double.toString(ku.getUkv()));
    }

    private double tampilIpk() {
        ControllerMahasiswa crl = new ControllerMahasiswa(152021169);
        double hasil = crl.getIpk();
        return hasil;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboard.setVisible(false);
        nilaiMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        dataMahasiswa.setVisible(true);
        tampilDataMahasiswa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        nilaiMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        dataMahasiswa.setVisible(false);
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dataMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(false);
        dashboard.setVisible(false);
        nilaiMahasiswa.setVisible(true);
        tampilNilai();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dataMahasiswa.setVisible(false);
        dashboard.setVisible(false);
        nilaiMahasiswa.setVisible(false);
        keuanganKuliah.setVisible(true);
        tampilKeuangan();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Percobaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Percobaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Percobaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Percobaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Percobaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dataMahasiswa;
    private javax.swing.JPanel dpp;
    private javax.swing.JLabel dpp_wajib;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel keuanganKuliah;
    private javax.swing.JPanel nilaiMahasiswa;
    private javax.swing.JPanel sidePanel;
    private View.TableDark tableDark1;
    private javax.swing.JLabel telat_pembayaran;
    private javax.swing.JLabel telat_perwalian;
    private javax.swing.JLabel ukt;
    private javax.swing.JPanel ukt1;
    private javax.swing.JLabel ukv;
    private javax.swing.JPanel ukv1;
    // End of variables declaration//GEN-END:variables
}
